<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ShiftCodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $shiftCodes = [
            // Status Non-Kerja/Cuti (Type: ALL)
            [
                'sc_code' => 'S',
                'sc_description' => 'Sakit',
                'sc_shift_name' => 'Sakit',
                'sc_start_time' => '00:00:00',
                'sc_end_time' => '00:00:00',
                'sc_type' => 'ALL',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'N/A',
                'sc_description' => 'Belum Disetting',
                'sc_shift_name' => 'Belum disetting',
                'sc_start_time' => '00:00:00',
                'sc_end_time' => '00:00:00',
                'sc_type' => 'ALL',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'LPH',
                'sc_description' => 'Libur Tgl Merah',
                'sc_shift_name' => 'Libur',
                'sc_start_time' => '00:00:00',
                'sc_end_time' => '00:00:00',
                'sc_type' => 'ALL',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'LL',
                'sc_description' => 'Libur Cuti',
                'sc_shift_name' => 'Libur',
                'sc_start_time' => '00:00:00',
                'sc_end_time' => '00:00:00',
                'sc_type' => 'ALL',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'L',
                'sc_description' => 'Libur',
                'sc_shift_name' => 'Libur',
                'sc_start_time' => '00:00:00',
                'sc_end_time' => '00:00:00',
                'sc_type' => 'ALL',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'I',
                'sc_description' => 'Izin',
                'sc_shift_name' => 'Izin',
                'sc_start_time' => '00:00:00',
                'sc_end_time' => '00:00:00',
                'sc_type' => 'ALL',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Shift Full-Time
            [
                'sc_code' => 'FSE',
                'sc_description' => 'Fulltime Sabtu Shift 2',
                'sc_shift_name' => 'Shift 2',
                'sc_start_time' => '13:45:00',
                'sc_end_time' => '21:59:00',
                'sc_type' => 'Full Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'FS2',
                'sc_description' => 'Fulltime Shift 2',
                'sc_shift_name' => 'Shift 2',
                'sc_start_time' => '13:15:00',
                'sc_end_time' => '21:29:00',
                'sc_type' => 'Full Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'FS1',
                'sc_description' => 'Fulltime Shift 1',
                'sc_shift_name' => 'Shift 1',
                'sc_start_time' => '09:45:00',
                'sc_end_time' => '17:59:00',
                'sc_type' => 'Full Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'FS0',
                'sc_description' => 'Fulltime Shift 0',
                'sc_shift_name' => 'Shift 0',
                'sc_start_time' => '07:30:00',
                'sc_end_time' => '15:59:00',
                'sc_type' => 'Full Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'FM2',
                'sc_description' => 'Fulltime Minggu Shift 2',
                'sc_shift_name' => 'Shift 2',
                'sc_start_time' => '16:00:00',
                'sc_end_time' => '21:59:00',
                'sc_type' => 'Full Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'FM1',
                'sc_description' => 'Fulltime Minggu Shift 1',
                'sc_shift_name' => 'Shift 1',
                'sc_start_time' => '10:00:00',
                'sc_end_time' => '15:59:00',
                'sc_type' => 'Full Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Shift Part-Time "Part Full"
            [
                'sc_code' => 'PFM',
                'sc_description' => 'Partime Full Sabtu Minggu',
                'sc_shift_name' => 'Full',
                'sc_start_time' => '10:15:00',
                'sc_end_time' => '21:59:00',
                'sc_type' => 'Part Full',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PF0',
                'sc_description' => 'Partime Full Shift 0',
                'sc_shift_name' => 'Full Shift 0',
                'sc_start_time' => '07:30:00',
                'sc_end_time' => '19:14:00',
                'sc_type' => 'Part Full',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PF',
                'sc_description' => 'Partime Full',
                'sc_shift_name' => 'Full',
                'sc_start_time' => '09:45:00',
                'sc_end_time' => '21:29:00',
                'sc_type' => 'Part Full',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Shift Part-Time
            [
                'sc_code' => 'SM2',
                'sc_description' => 'Weekend Partime Shift 2',
                'sc_shift_name' => 'Shift 2',
                'sc_start_time' => '16:00:00',
                'sc_end_time' => '21:59:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'SM1',
                'sc_description' => 'Weekend Partime Shift 1',
                'sc_shift_name' => 'Shift 1',
                'sc_start_time' => '08:45:00',
                'sc_end_time' => '14:44:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PS2',
                'sc_description' => 'Partime Shift 2',
                'sc_shift_name' => 'Shift 2',
                'sc_start_time' => '15:30:00',
                'sc_end_time' => '21:29:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PS1',
                'sc_description' => 'Partime Shift 1',
                'sc_shift_name' => 'Shift 1',
                'sc_start_time' => '09:45:00',
                'sc_end_time' => '15:44:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PS0',
                'sc_description' => 'Partime Shift 0',
                'sc_shift_name' => 'Shift 0',
                'sc_start_time' => '07:30:00',
                'sc_end_time' => '13:29:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PL2',
                'sc_description' => 'Parttime Long Shift 2',
                'sc_shift_name' => 'Shift 2',
                'sc_start_time' => '14:30:00',
                'sc_end_time' => '21:59:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sc_code' => 'PL1',
                'sc_description' => 'Parttime Long Shift 1',
                'sc_shift_name' => 'Shift 1',
                'sc_start_time' => '08:45:00',
                'sc_end_time' => '16:14:00',
                'sc_type' => 'Part Time',
                'sc_status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('shift_codes')->insert($shiftCodes);
    }
} 