version: '3.8'
services:
  jezsistem_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jezsistem_app
    container_name: jezsistem_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: jezsistem_app
      SERVICE_TAGS: production
      DB_CONNECTION: mysql
      DB_HOST: tahulahh_mariadb
      DB_PORT: 3306
      DB_DATABASE: tahulahh_db
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_RECAPTCHA_KEY: 6LcEptkpAAAAAAMsklLOIz3N6rrR43t35j_jDO8x
      GOOGLE_RECAPTCHA_SECRET: 6LcEptkpAAAAAD8IRrXXYsX68ggNenee-EPvpBFe
    working_dir: /var/www/jezsistem_app
    volumes:
      - .:/var/www/jezsistem_app
      # - shared_jezsistem_app:/var/www/jezsistem_app
    networks:
      - s3_network
    ports:
      - "81:80"

networks:
  s3_network:
    driver: bridge
    name: s3_network