<?php

namespace Database\Seeders\Users;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserFrontlineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $menuAccess1 = [
            78 => 'Dashboard',
            79 => 'Dashboard V2',
            80 => 'Data Store',
            81 => 'Data Divisi',
            82 => 'Data Supplier',
            83 => 'Artikel Brand',
            84 => 'Artikel Unit',
            85 => 'Artikel Gender',
            86 => 'Artikel Season',
            87 => 'Artikel Kategori',
            88 => 'Artikel Sub Kategori',
            89 => 'Artikel Sub Sub Kategori',
            90 => 'Artikel Warna',
            91 => 'Skema Size',
            92 => 'Data Artikel',
            93 => 'Lokasi Simpan / BIN',
            102 => 'Pembelian',
            103 => 'Penerimaan',
            104 => 'Approval Penerimaan',
            105 => 'Helper App',
            106 => 'Setup Store Aging',
            110 => 'Instock & Exception Approval',
            111 => 'Instock Waiting List',
            112 => 'SO Adjustment',
            113 => 'Scan Adjustment',
            114 => 'Manual Adjustment',
            115 => 'Exception Location',
            116 => 'B1G1 Location (Direct Pick)',
            117 => 'ECommerce Qty Exception',
            118 => 'Stok Pada BIN',
            119 => 'Setup Lokasi Stok',
            120 => 'Transfer Stok',
            121 => 'Penerimaan Transfer',
            122 => 'Data Stok',
            123 => 'Stock Tracking',
            124 => 'POS App',
            125 => 'Invoice Editor',
            126 => 'Data Nameset',
            // 127 => 'Setup Target',
            128 => 'Setup Diskon',
            129 => 'Setup Voucher',
            130 => 'Sales Summary',
            131 => 'Cross Order',
            132 => 'Invoice Tracking',
            143 => 'Asset Detail',
             145 => 'Data Customer',
            146 => 'Rating By Customer (tab)',
            147 => 'Tampilan Rating',
            148 => 'Laporan Penjualan',
            149 => 'Laporan Stok',
            150 => 'Laporan Summary',
            151 => 'Laporan Barang Datang',
            168 => 'Blast Whatsapp',
            169 => 'Marketplace Manager',
            170 => 'Store Traffic',
            171 => 'Pre Order'
        ];

        $menuAccess2 = [
             78 => 'Dashboard',
             79 => 'Dashboard V2',
            105 => 'Helper App',
             124 => 'POS App',
             126 => 'Data Nameset',
             145 => 'Data Customer',
            148 => 'Laporan Penjualan',
            156 => 'ECom Transaksi',
             157 => 'ECom Konfirmasi',
             169 => 'Marketplace Manager',
             170 => 'Store Traffic',
        ];

        $usersData = [
            [
                'u_name' => 'ACHMAD BAGASKARA N.',
                'u_email' => 'achmadbagaskara9@jez.co.id',
                'u_phone' => '085733369356',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 4,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'WAHYU FIRMANSYAH',
                'u_email' => 'fsyah1234@jez.co.id',
                'u_phone' => '085745917953',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 4,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'BARA GUSNALDI',
                'u_email' => 'gusnaldibara5@jez.co.id',
                'u_phone' => '085704016055',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 5,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'FRANKY WAHYU',
                'u_email' => 'frankywahyu21@jez.co.id',
                'u_phone' => '085746652741',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'PUTRI PRAMITASARI',
                'u_email' => 'putripramita090@jez.co.id',
                'u_phone' => '0895366896413',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 2,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MARIZKA DHIA AYU N S',
                'u_email' => 'marizkasandy23@jez.co.id',
                'u_phone' => '087810711431',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD AGIL SOFIANUR',
                'u_email' => 'muhammadagilsofianur@jez.co.id',
                'u_phone' => '085791538225',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];
        $usersData2 = [
            [
                'u_name' => 'SALSABILA DWI PUTRI ADHADIANTI',
                'u_email' => 'salsadpa1302@jez.co.id',
                'u_phone' => '089503418200',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 4,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'SHINTIA WATI DJINI MANTROS',
                'u_email' => 'sintiatia517@jez.co.id',
                'u_phone' => '083846140245',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 4,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD FAHMI',
                'u_email' => 'muhfahmi2366@jez.co.id',
                'u_phone' => '085234275806',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 4,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'SYAHRUL RAMADHAN',
                'u_email' => 'syahrulramadhan221102@jez.co.id',
                'u_phone' => '085399622670',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 5,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'FAZA ITSNANI HIDAYAT',
                'u_email' => 'isnanifaza@jez.co.id',
                'u_phone' => '087732742346',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 5,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'PANDU PURBO DEWANGGA',
                'u_email' => 'pandudewangga12@jez.co.id',
                'u_phone' => '081391484566',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 5,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'VIONA CINTHIA MARGARETHA',
                'u_email' => 'vionacinthiamargaretha@jez.co.id',
                'u_phone' => '082330359035',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 5,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD LABIYB NAUFAL',
                'u_email' => 'abynaufal44@jez.co.id',
                'u_phone' => '085730740570',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'NATALIA RACHEL P A N',
                'u_email' => 'nataliarachel1012@jez.co.id',
                'u_phone' => '0895601024952',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'VISI MIRANDA S M',
                'u_email' => 'visimiranda17@jez.co.id',
                'u_phone' => '081334180933',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD NAUFAL P W',
                'u_email' => 'naufalwibowo14@jez.co.id',
                'u_phone' => '085700925288',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD MAULANA TITOFANI',
                'u_email' => 'maulanatito2323@jez.co.id',
                'u_phone' => '085163111091',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ARDIANSYAH',
                'u_email' => 'Ardiisyah75@jez.co.id',
                'u_phone' => '082131194855',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ANGGITA NUR RIZQIANA',
                'u_email' => 'anggita.rizqiana@jez.co.id',
                'u_phone' => '089669717313',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'SATRIA BAYU PANUTAN',
                'u_email' => 'Bayupanutan0@jez.co.id',
                'u_phone' => '082257452915',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'SITI AISAH',
                'u_email' => 'sitiaisahsby28@jez.co.id',
                'u_phone' => '089528419825',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'TIRMIDZI HARRY DWI YANTO',
                'u_email' => 'tirmidziharry@jez.co.id',
                'u_phone' => '081259325628',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'RYAN APRIE ESA WICAKSANA',
                'u_email' => 'ryanaprieesa@jez.co.id',
                'u_phone' => '081615530463',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 2,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
//            [
//                'u_name' => 'GEBY FEBRIAN PRATAMA',
//                'u_email' => 'gebypratama24@jez.co.id',
//                'u_phone' => '081945792601',
//                'password' => bcrypt('123'),
//                'delete_access' => '0',
//                'st_id' => 20,
//                'stt_id' => 1,
//                'u_secret_code' => '123',
//                'group_id' => 2,
//            ],
            [
                'u_name' => 'MELATI INDIRA PUTRI CHANDRA',
                'u_email' => 'melatiindira7@jez.co.id',
                'u_phone' => '08813143602',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'INEKKE ADELIA',
                'u_email' => 'ineke.adelia52@jez.co.id',
                'u_phone' => '088216927478',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'NUR AISYIAH',
                'u_email' => 'shashaaisyah45@jez.co.id',
                'u_phone' => '085790589167',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'DIA DEWI ROBI\'AH',
                'u_email' => 'dewidiyyah@jez.co.id',
                'u_phone' => '081450044867',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ATRIA AYU ADHARA',
                'u_email' => 'atriaayu@jez.co.id',
                'u_phone' => '082234695953',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ANNISA ALIF PAWITRA',
                'u_email' => 'Annisa.alifpawitra@jez.co.id',
                'u_phone' => '088217848050',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'NAZILATUL MAZIYAH',
                'u_email' => 'anasnazila1@jez.co.id',
                'u_phone' => '085234006522',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 20,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'DIVANYA MICHELLE',
                'u_email' => 'divanya.dd06@jez.co.id',
                'u_phone' => '081336999722',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ANGGI EVIANA SANSA',
                'u_email' => 'anggieviana795@jez.co.id',
                'u_phone' => '089529868990',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'CLAUDINCIA CHRISTINA A F',
                'u_email' => 'claudinciachristina@jez.co.id',
                'u_phone' => '085722741972',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ELVIEKA WIDYAPANGESTU',
                'u_email' => 'Pangestuviar@jez.co.id',
                'u_phone' => '0895623522719',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'RAHMA TIARA MAHARANI',
                'u_email' => 'rahmatiaramhrn@jez.co.id',
                'u_phone' => '085843786448',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 30,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
//            [
//                'u_name' => 'MUHAMMAD ALWY TAUFIQ',
//                'u_email' => 'alwiitaufiq@jez.co.id',
//                'u_phone' => '089680819122',
//                'password' => bcrypt('123'),
//                'delete_access' => '0',
//                'st_id' => 2,
//                'stt_id' => 1,
//                'u_secret_code' => '123',
//                'group_id' => 2,
//            ],
//            [
//                'u_name' => 'JAKA WALI GILANG PRAYOGA',
//                'u_email' => 'gilanggak5@jez.co.id',
//                'u_phone' => '085852457882',
//                'password' => bcrypt('123'),
//                'delete_access' => '0',
//                'st_id' => 2,
//                'stt_id' => 1,
//                'u_secret_code' => '123',
//                'group_id' => 2,
//            ],
            [
                'u_name' => 'BIMO AJI ARIO PUTRO',
                'u_email' => 'bimoaji57@jez.co.id',
                'u_phone' => '085157466706',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 2,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ENDHITO WAHYU D',
                'u_email' => 'endhitowahyu22@jez.co.id',
                'u_phone' => '08951869700',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 2,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'AULIA YUNIAR',
                'u_email' => 'auliayuniar321@jez.co.id',
                'u_phone' => '085735618675',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 2,
                'stt_id' => 1,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];


        $this->insertUserData($usersData, $menuAccess1);
        $this->insertUserData($usersData2, $menuAccess2);
    }


    private function insertUserData(array $dataUsers, array $dataUserMenuAccess)
    {
        foreach ($dataUsers as $dataUser) {
            $user_id = DB::table('users')->insertGetId([
                'u_name' => $dataUser['u_name'],
                'u_email' => $dataUser['u_email'],
                'u_phone' => $dataUser['u_phone'],
                'password' => $dataUser['password'],
                'delete_access' => $dataUser['delete_access'],
                'st_id' => $dataUser['st_id'],
                'stt_id' => $dataUser['stt_id'],
                'u_secret_code' => $dataUser['u_secret_code'],
            ]);

            DB::table('user_groups')->insert([
                'user_id' => $user_id,
                'group_id' => $dataUser['group_id'],
            ]);

            foreach ($dataUserMenuAccess as $menuKey => $menuValue) {
                $uma_default = ($menuValue == 'Dashboard') ? '1' : '0';

                DB::table('user_menu_accesses')->insert([
                    'u_id' => $user_id,
                    'ma_id' => $menuKey,
                    'uma_default' => $uma_default,
                ]);
            }
        }
    }
}
