<?php

namespace Database\Seeders\Users;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserBackOfficeSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Hak Akses ALL
         */

        $data = [
            78 => 'Dashboard',
            79 => 'Dashboard V2',
            80 => 'Data Store',
            81 => 'Data Divisi',
            82 => 'Data Supplier',
            83 => 'Artikel Brand',
            84 => 'Artikel Unit',
            85 => 'Artikel Gender',
            86 => 'Artikel Season',
            87 => 'Artikel Kategori',
            88 => 'Artikel Sub Kategori',
            89 => 'Artikel Sub Sub Kategori',
            90 => 'Artikel Warna',
            91 => 'Skema Size',
            92 => 'Data Artikel',
            93 => 'Lokasi Simpan / BIN',
            94 => 'Jenis Akun',
            95 => 'Klasifikasi Akun',
            96 => 'Data Akun',
            97 => 'Data Pajak',
            98 => 'Tipe Stok',
            99 => 'Metode Pembayaran',
            100 => 'Kurir Pengiriman',
            101 => 'Daftar Hutang',
            102 => 'Pembelian',
            103 => 'Penerimaan',
            104 => 'Approval Penerimaan',
            105 => 'Helper App',
            106 => 'Setup Store Aging',
            107 => 'Menu Access',
            108 => 'Data User',
            109 => 'Data User By Divisi',
            110 => 'Instock & Exception Approval',
            111 => 'Instock Waiting List',
            112 => 'SO Adjustment',
            113 => 'Scan Adjustment',
            114 => 'Manual Adjustment',
            115 => 'Exception Location',
            116 => 'B1G1 Location (Direct Pick)',
            117 => 'ECommerce Qty Exception',
            118 => 'Stok Pada BIN',
            119 => 'Setup Lokasi Stok',
            120 => 'Transfer Stok',
            121 => 'Penerimaan Transfer',
            122 => 'Data Stok',
            123 => 'Stock Tracking',
            124 => 'POS App',
            125 => 'Invoice Editor',
            126 => 'Data Nameset',
            127 => 'Setup Target',
            128 => 'Setup Diskon',
            129 => 'Setup Voucher',
            130 => 'Sales Summary',
            131 => 'Cross Order',
            132 => 'Invoice Tracking',
            135 => 'Data Reseller',
            143 => 'Asset Detail',
            145 => 'Data Customer',
            146 => 'Rating By Customer (tab)',
            147 => 'Tampilan Rating',
            148 => 'Laporan Penjualan',
            149 => 'Laporan Stok',
            150 => 'Laporan Summary',
            151 => 'Laporan Barang Datang',
            152 => 'Main Menu',
            153 => 'Pengaturan ERP',
            154 => 'Data User Report',
            155 => 'Hasil Rating Kasir',
            156 => 'ECom Transaksi',
            157 => 'ECom Konfirmasi',
            158 => 'ECom Artikel',
            159 => 'ECom Topdeals',
            160 => 'ECom Banner',
            161 => 'ECom Bank',
            162 => 'ECom Slug Brand',
            163 => 'ECom Slug Kategori',
            164 => 'ECom Slug Sub Kategori',
            165 => 'ECom Setup Free Ongkir',
            166 => 'ECom Customer Ingatkan',
            167 => 'ECom BLOG',
            168 => 'Blast Whatsapp',
            169 => 'Marketplace Manager',
            170 => 'Store Traffic',
            171 => 'Pre Order'
        ];
        $menuAccessHRGAFINANCE = [
            78 => 'Dashboard',
            79 => 'Dashboard V2',
            80 => 'Data Store',
            81 => 'Data Divisi',
            82 => 'Data Supplier',
            83 => 'Artikel Brand',
            84 => 'Artikel Unit',
            85 => 'Artikel Gender',
            86 => 'Artikel Season',
            87 => 'Artikel Kategori',
            88 => 'Artikel Sub Kategori',
            89 => 'Artikel Sub Sub Kategori',
            90 => 'Artikel Warna',
            91 => 'Skema Size',
            92 => 'Data Artikel',
            93 => 'Lokasi Simpan / BIN',
            94 => 'Jenis Akun',
            95 => 'Klasifikasi Akun',
            96 => 'Data Akun',
            97 => 'Data Pajak',
            98 => 'Tipe Stok',
            99 => 'Metode Pembayaran',
            100 => 'Kurir Pengiriman',
            101 => 'Daftar Hutang',
            102 => 'Pembelian',
            103 => 'Penerimaan',
            104 => 'Approval Penerimaan',
            105 => 'Helper App',
            106 => 'Setup Store Aging',
            108 => 'Data User',
            109 => 'Data User By Divisi',
            110 => 'Instock & Exception Approval',
            111 => 'Instock Waiting List',
            112 => 'SO Adjustment',
            113 => 'Scan Adjustment',
            114 => 'Manual Adjustment',
            115 => 'Exception Location',
            116 => 'B1G1 Location (Direct Pick)',
            117 => 'ECommerce Qty Exception',
            118 => 'Stok Pada BIN',
            119 => 'Setup Lokasi Stok',
            120 => 'Transfer Stok',
            121 => 'Penerimaan Transfer',
            122 => 'Data Stok',
            123 => 'Stock Tracking',
            124 => 'POS App',
            125 => 'Invoice Editor',
            126 => 'Data Nameset',
            127 => 'Setup Target',
            128 => 'Setup Diskon',
            129 => 'Setup Voucher',
            130 => 'Sales Summary',
            131 => 'Cross Order',
            132 => 'Invoice Tracking',
            135 => 'Data Reseller',
            143 => 'Asset Detail',
            145 => 'Data Customer',
            146 => 'Rating By Customer (tab)',
            147 => 'Tampilan Rating',
            148 => 'Laporan Penjualan',
            149 => 'Laporan Stok',
            150 => 'Laporan Summary',
            151 => 'Laporan Barang Datang',
            154 => 'Data User Report',
            155 => 'Hasil Rating Kasir',
            168 => 'Blast Whatsapp',
            169 => 'Marketplace Manager',
            170 => 'Store Traffic',
            171 => 'Pre Order'
        ];
        $menuAccess3 = [
            78 => 'Dashboard',
            79 => 'Dashboard V2',
            80 => 'Data Store',
            81 => 'Data Divisi',
            82 => 'Data Supplier',
            83 => 'Artikel Brand',
            84 => 'Artikel Unit',
            85 => 'Artikel Gender',
            86 => 'Artikel Season',
            87 => 'Artikel Kategori',
            88 => 'Artikel Sub Kategori',
            89 => 'Artikel Sub Sub Kategori',
            90 => 'Artikel Warna',
            91 => 'Skema Size',
            92 => 'Data Artikel',
            93 => 'Lokasi Simpan / BIN',
            102 => 'Pembelian',
            103 => 'Penerimaan',
            104 => 'Approval Penerimaan',
            105 => 'Helper App',
            106 => 'Setup Store Aging',
            110 => 'Instock & Exception Approval',
            111 => 'Instock Waiting List',
            112 => 'SO Adjustment',
            113 => 'Scan Adjustment',
            114 => 'Manual Adjustment',
            115 => 'Exception Location',
            116 => 'B1G1 Location (Direct Pick)',
            117 => 'ECommerce Qty Exception',
            118 => 'Stok Pada BIN',
            119 => 'Setup Lokasi Stok',
            120 => 'Transfer Stok',
            121 => 'Penerimaan Transfer',
            122 => 'Data Stok',
            123 => 'Stock Tracking',
            124 => 'POS App',
            125 => 'Invoice Editor',
            126 => 'Data Nameset',
            127 => 'Setup Target',
            128 => 'Setup Diskon',
            129 => 'Setup Voucher',
            130 => 'Sales Summary',
            131 => 'Cross Order',
            132 => 'Invoice Tracking',
            143 => 'Asset Detail',
            145 => 'Data Customer',
            146 => 'Rating By Customer (tab)',
            147 => 'Tampilan Rating',
            148 => 'Laporan Penjualan',
            149 => 'Laporan Stok',
            150 => 'Laporan Summary',
            151 => 'Laporan Barang Datang',
            168 => 'Blast Whatsapp',
            169 => 'Marketplace Manager',
            170 => 'Store Traffic',
            171 => 'Pre Order'
        ];

        $usersData = [
            [
                'u_name' => 'HENDRA SETIAWAN',
                'u_email' => 'hendra.setiawan12594@jez.co.id',
                'u_phone' => '081235803523',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 15,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ZAKKI SAFRIZAL Z',
                'u_email' => 'zakkisafrizal@jez.co.id',
                'u_phone' => '085645959060',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 15,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'JOSEPH KENOLY N',
                'u_email' => 'kenny13_pwners71@jez.co.id',
                'u_phone' => '081336581300',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 15,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];
        $usersDataHrgaFinance = [
            [
                'u_name' => 'SERLI YUSNIATUR R',
                'u_email' => 'Sherlyyusniaturr@jez.co.id',
                'u_phone' => '085645279464',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 12,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'VIRA LUTHFIA PRATIWI',
                'u_email' => 'viraluthfiaa10@jez.co.id',
                'u_phone' => '087896348924',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 12,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'NI MADE CANDRA DEWI',
                'u_email' => 'mdcndradw@jez.co.id',
                'u_phone' => '085754865455',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 12,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'CANDRA WAHYUDI',
                'u_email' => 'candwahyudi06@jez.co.id',
                'u_phone' => '082151444749',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 12,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],



        ];
        $userLogistikMalang = [
            [
                'u_name' => 'AGUS KURNIAWAN',
                'u_email' => 'ktoking615@gmail.co.id',
                'u_phone' => '085707259424',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 13,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'RIZAL FIKRI CHOIRUDIN',
                'u_email' => 'choirudinn4@jez.co.id',
                'u_phone' => '081357157698',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 13,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ARIS PRATAMA',
                'u_email' => 'Arispratama1407@jez.co.id',
                'u_phone' => '082230223584',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 13,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'ALFAN ZUHDI ASSYURA',
                'u_email' => 'alfanassyura@jez.co.id',
                'u_phone' => '085159011402',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 13,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'REYHAN IVAN ADITYA',
                'u_email' => 'reyhanvaan@jez.co.id',
                'u_phone' => '085234108109',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 13,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'RAHDIANDY ARTHA M',
                'u_email' => 'artharahdian@jez.co.id',
                'u_phone' => '085606936864',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 13,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];
        $userLogistikSurabya = [
            [
                'u_name' => 'MOCHAMMAD RENO S',
                'u_email' => 'renotok07@jez.co.id',
                'u_phone' => '08885462705',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 14,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD TEDDY F',
                'u_email' => 'teddyfernando048@jez.co.id',
                'u_phone' => '082149460929',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 14,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'DWIKI ADENSA',
                'u_email' => 'dwiki.adensa1412@jez.co.id',
                'u_phone' => '085648766718',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 14,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'NICA PUTRA WIJAYA',
                'u_email' => 'nicaputra03@jez.co.id',
                'u_phone' => '085176836626',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 14,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'IZZA MABRUR ILLIYIN',
                'u_email' => 'izzamabrurilliyin@jez.co.id',
                'u_phone' => '089677181723',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 14,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];
        $userPurchasing = [
            [
                'u_name' => 'SABRIANTO',
                'u_email' => 'riansabrianto97@jez.co.id',
                'u_phone' => '08557927875',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 18,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'DONA REGI ARY I D P',
                'u_email' => 'donaregi71@jez.co.id',
                'u_phone' => '085749339028',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 18,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];
        $userSuperVisor = [
            [
                'u_name' => 'HARDHIKA PRATAMA',
                'u_email' => 'hardhikapratamaa@jez.co.id',
                'u_phone' => '081230801096',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 3,
                'stt_id' => 17,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'BANGKIT YONGKI S N',
                'u_email' => 'bangkityongki20@jez.co.id',
                'u_phone' => '083846611545',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 17,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'NURUL MUKHLIS',
                'u_email' => 'nurulmukhlis07@jez.co.id',
                'u_phone' => '081230801096',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 17,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];
        $userMarkom = [
            [
                'u_name' => 'JOSEP RIDHO S',
                'u_email' => 'ridhojosep@jez.co.id',
                'u_phone' => '081358000203',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MIFTAH RISKI P',
                'u_email' => 'yoginogi@jez.co.id',
                'u_phone' => '085888075944',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'YASMIN FAIRUZ Z',
                'u_email' => 'yasminfairuzz@jez.co.id',
                'u_phone' => '085850362933',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD NAUFAL R',
                'u_email' => 'rafisyahnaufal@jez.co.id',
                'u_phone' => '089697669082',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'SAFARAZ RAFI K',
                'u_email' => 'safarazrafi@jez.co.id',
                'u_phone' => '085785140973',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MOCH. DIHAN A M',
                'u_email' => 'masdihanaly@jez.co.id',
                'u_phone' => '085161540453',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD RIZKY',
                'u_email' => 'muhammadrizky160698@jez.co.id',
                'u_phone' => '081316536460',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'SEBASTIAN RAMADHAN',
                'u_email' => 'sebastianramadhn@jez.co.id',
                'u_phone' => '083157155686',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
            [
                'u_name' => 'MUHAMMAD ABINURRACHMAN C',
                'u_email' => 'muhammadabinurrachman@jez.co.id',
                'u_phone' => '0859180774713',
                'password' => bcrypt('123'),
                'delete_access' => '0',
                'st_id' => 1,
                'stt_id' => 19,
                'u_secret_code' => '123',
                'group_id' => 2,
            ],
        ];

        $this->insertUserData($usersData, $data);
        $this->insertUserData($usersDataHrgaFinance, $menuAccessHRGAFINANCE);
        $this->insertUserData($userLogistikMalang, $menuAccess3);
        $this->insertUserData($userLogistikSurabya, $menuAccess3);
        $this->insertUserData($userPurchasing, $menuAccess3);
        $this->insertUserData($userSuperVisor, $menuAccess3);
        $this->insertUserData($userMarkom, $menuAccess3);
    }

    private function insertUserData(array $dataUsers, array $dataUserMenuAccess)
    {
        foreach ($dataUsers as $dataUser) {
            $user_id = DB::table('users')->insertGetId([
                'u_name' => $dataUser['u_name'],
                'u_email' => $dataUser['u_email'],
                'u_phone' => $dataUser['u_phone'],
                'password' => $dataUser['password'],
                'delete_access' => $dataUser['delete_access'],
                'st_id' => $dataUser['st_id'],
                'stt_id' => $dataUser['stt_id'],
                'u_secret_code' => $dataUser['u_secret_code'],
            ]);

            DB::table('user_groups')->insert([
                'user_id' => $user_id,
                'group_id' => $dataUser['group_id'],
            ]);

            foreach ($dataUserMenuAccess as $menuKey => $menuValue) {
                $uma_default = ($menuValue == 'Dashboard') ? '1' : '0';

                DB::table('user_menu_accesses')->insert([
                    'u_id' => $user_id,
                    'ma_id' => $menuKey,
                    'uma_default' => $uma_default,
                ]);
            }
        }
    }
}
